version: '3.8'

services:
  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: dbmainsell
      MYSQL_USER: isaiasiotti
      MYSQL_PASSWORD: isaias963
    ports:
      - "3307:3307"
    